# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDQ5Yzc5ZWM0MjcwNjYwNjAyMjZhZDBhOTk1N2FhNTc4YjQ2MjU2NWU0M2E5NzRmMjRmZWJmN2YxMjk0MDZmN2MyZjM2YWVlZGFjNDcyNjAzYmU3YjgyNzVkMTUwYTU3MTFkZWEzNDEyNjIwOWQ5NGFkODA4M2M1MzczMDEzMGU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
